### ISSUE TITLE
auth.js authorise(packageData, tokenKey) fails if optional tokenKey is omitted

### ISSUE THREAD

**Issue by theWebalyst** [joshuef/safe-js#10]
README.md says auth.js authorise(packageData, tokenKey) where tokenKey is "optional", but if tokenKey is omitted and the browser has local storage, then getAuthToken( tokenString ) below will be called with tokenString undefined, which is an error: 

```
export const authorise = function( packageData, token )
{   
    let tokenString = token;

    // for beaker only. Otherwise use localStorage.
    if( !localStorageExists && this && this.sender )
    {
        // get the webcontents url
        const wholeUrl = this.sender.getURL()
        const parsedUrl = url.parse( wholeUrl );
        tokenString = parsedUrl.hostname;
        
        //override vendor with the url?
        if( packageData )
            packageData.vendor = wholeUrl;
        
    }
    
let tokenFromStorage = getAuthToken( tokenString );
```
See: https://github.com/joshuef/safe-js/blob/master/src/auth.js#L60-L78

**Comment by joshuef** [comment]
Hmmm. Yeh right now this is a problem.

The ideal is that safejs could be used in any situation, so there's functionality for it being included in the browser, which can differ from beaker.

Your question makes me think though, perhaps we shouldn't be handling any localStorage for the user. If auth simply returns a token, to be handled by the user, everything would be much cleaner.

And as it stands this functionality is *only* utilised by `auth.js` anyway...

So, I think actually removing this localStorage helper function would make a lot of sense, clean up the code and confusion here.

Can you see any reason not to progress in this fashion, @theWebalyst?

**Comment by theWebalyst** [comment]
I agree, to remove it seems sensible. I think it is something best explicitly handled by the app, not hidden in a library. There's no reason not to provide a separate helper/helpers (e.g. to encourage secure or sensible handling of tokens in browser storage), but hiding what's happening seems more unhelpful than helpful :-)

**Comment by joshuef** [comment]
Grand: Then I'll clean this and the confusion out.

**Comment by joshuef** [comment]
This is sorted via the above commit (yet to be merged with master). 

I'll be tying this in with the beaker-plugin-safe update to wrap beaker specific mods of this in an upcoming Safe Browser release 👍 .

Auth should be *muchhh* cleaner and clearer now. Only one thing to pass.

**Comment by frabrunelle** [comment]
very nice! I definitely prefer the new code, it's much cleaner and easier to understand 😃

**Comment by joshuef** [comment]
Yeh. Wrapping this into beaker helps *a lot* here 👍
