### ISSUE TITLE
Support for FFI error and HTTP status codes returned by safe-js

### ISSUE THREAD

**Issue by theWebalyst** [joshuef/safe-js#14]
### Testing FFI err.errorCode
I'm thinking it is not good practice to test for hard coded values such as -1503 (FfiError::InvalidPath) so propose that safe-js provide a way to test meaningful names against err.errorCode returns.

For example:
```
if ( safeError.InvalidPath == err.errorCode )
   {
   }
```

### Testing HTTP Response Status
Also, with the switch to safe-js we've lost the launcher HTTP response codes which are useful and it would be nice if each app that wants them didn't have to work out their own mapping.

So can we either add in ```err.HttpStatusCode``` or provide a mapping function ```safeError.HttpStatusCode( err.errorCode )```?

**Comment by joshuef** [comment]
Hey @theWebalyst Actually, in the last safe-js update it's (at least for the 'trad' endpoints AUTH/NFS/DNS) now returning the launcher HTTP codes where it can: https://github.com/joshuef/safe-js/blob/master/src/utils.js#L12-L24 . Which is indeed much more general and useful. 

Totally agree with you here and the plan is to expand this to all endpoints. Going to close this in favour of a more specific: https://github.com/joshuef/safe-js/issues/15.

**Comment by theWebalyst** [comment]
Thanks @joshuef, this is good news :), can you show me how to access this - using beaker 0.3.6 yesterday I examined the Err object and didn't see a way to access an HTTP error response.
