### ISSUE TITLE
safeNFS is missing Update file

### ISSUE THREAD

**Issue by theWebalyst** [joshuef/safe-js#6]
The NFS REST API supports POST (create file) and PUT (update file) but safe-js does not support the latter.

**Comment by theWebalyst** [comment]
Or... maybe it is just the docs which are out of date? ...as I see I have a note that POST is now used for both create and update. This might need reflecting in the safeNFS method (e.g. as safeNDS.CreateOrUpdateFile() or a note that it does both).

**Comment by joshuef** [comment]
@theWebalyst as I understand it, the API update is only for metadata (https://api.safedev.org/nfs/file/update-file-metadata.html), not the file itself, so the current setup requires a delete/create of the file. ( @gnunicorn please let me know if that's not the case)

But I'm with you here, I think we should at least be adding to safejs as a helper function for an update until a real update is available for files 👍

**Comment by theWebalyst** [comment]
Hmm @joshuef you may well be right, but looking at the docs it isn't clearly stated. 

I have a comment in my code that the create file endpoint was changed to do both create and update, but I haven't tested and it isn't stated that a file must not exist for create to succeed so I'm not sure. Guess I should test this to see what happens! :-)

**Comment by frabrunelle** [comment]
@theWebalyst it's explained here: https://api.safedev.org/nfs/file/ 🙂

> The update file endpoint has been temporarily deprecated.

**Comment by theWebalyst** [comment]
Thanks @frabrunelle
