### ISSUE TITLE
safeNFS.getDir never provides body in response

### ISSUE THREAD

**Issue by theWebalyst** [joshuef/safe-js#7]
Example is getDir on drive for '/' - returns 200/OK but no response.resposeText (or body)

Francis took a look and thinks it needs a parseResponse (or something).

**Comment by theWebalyst** [comment]
Here is Francis' comment:
> I think I found the error. he needs to add "parseResponse" like he did for the DNS API: https://github.com/joshuef/safe-js/blob/master/src/dns.js#L69

**Comment by theWebalyst** [comment]
I've tried modifying safe-js getDir (as Francis suggests) in a local copy of safe-beaker, but I'm still having this problem. 

I then noticed I had the polyfill.js in index.html and modified getDir inside that. Same problem.  (Setting a breakpoint in polyfill.js suggests it is not being used - I'm running live on Test10 at safe://myfd.rsports).

So either I'm not modifying safe-js getDir successfully or the above change hasn't fixed this issue, I'm not sure which. Anyway I'm stuck!

**Comment by joshuef** [comment]
Just FYI, there's two tweaks coming here soon: `getDNS` will be renamed to `listLongNames` as that fits with the actual API specs (getDNS was deprecated after 0.5 or so).

And safe-js will automatically parse the response on success, providing the relevant data. On fail, it will simply reject the promise and return the response from the server so you can utilise all the info therein.

**Comment by joshuef** [comment]
@theWebalyst I've started this in the promiseImprovements branch:
https://github.com/joshuef/safe-js/commit/5464cfcf88c1d6d13241711375b3f1e1a6293c0f

You can checkout that branch and test if you'd like. I need to update and test a lot of functionality before I can push this into master though, fyi.

**Comment by gnunicorn** [comment]
@theWebalyst I believe the polyfill is – as any polyfill does – only being used when the API can't be found. Try using it from localhost, where the DOM API isn't exposed yet.

**Comment by theWebalyst** [comment]
Thanks @gnunicorn, still learning :)

The issue is then only with beaker safe-js although it had been fixed in 0.3.6.
