### ISSUE TITLE
window.safeAuth.authorise() in beaker doesn't return a token

### ISSUE THREAD

**Issue by theWebalyst** [joshuef/safe-js#9]
I have had some success authorising with beaker/safe-js but it seems easy for me to get into a state where ```window.safeAuth.authorise(...).then( function (res) {...} )``` succeeds, but fails to return a token:

I see
```res.checkedOut``` is true
but
```res.token``` is undefined

Am I right in thinking that if ```res.checkedOut``` is true, ```res.token``` can be expected to be defined (and valid)? If so I guess that's a safe-js bug?

Hopefully if this is a safe-js bug you can diagnose and fix just by inspecting the code. If not you might be able to reproduce it by using my safe://myfd.rsports app on Test10.

### How To Reproduce
Assuming a safe-js bug I'm not sure how to reproduce it but think that it might be once the token has been obtained and is available in localStorage that this can happen. What I'm doing is reloading my safe://myfd.rsports app (Test 10) so you could try to reproduce with that and see the result within     ```safenetworkAuthorize: function (appApiKeys) {...}``` in remotestorage.js as follows:

Start SAFE Launcher and login to Test10 network
Start beaker, open beaker dev tools and visit safe://myfd.rsports
Watch the console
Create a drink in the app
click the blue icon top right, authorise in Launcher

Watch the console for it working, which is indicated by it trying to sync with safe storage every 10s. If it is working there will be a burst of output every ten seconds although the code is failing, the sync will continue. Unfortunately this condition won't show the undefined token bug reported above. So you'll have to find a way to get to the state where the token is not returned.

If it is not syncing every 10s. This is normal (but a bug in the app), but you can usually trigger it by Ctrl-Shift-R the App and also clicking on the SAFE icon (top right) to try and get it to connect.

Correct sync means you won't be seeing the undefined token bug.
Failing to try and sync may still mean you won't see this bug.

The question is how to get from either of the above two states to the third state where there is no sync happening and each click on the SAFE icon results in ```window.safeAuth.authorise(...)``` to return ```res.token``` undefined while ```res.checkedOut``` is true (all the time at the moment). That, I'm not sure.

Probably irrelevant, but I am using a custom build of beaker where I have changed nfs.js ```getDir()```:
```
return response
```
to
```
return parseResponse(response);
```
in order to fix issue https://github.com/joshuef/safe-js/issues/7

**Comment by frabrunelle** [comment]
Have you tried looking at `res.__parsedResponseBody__.token`? that's what the comments plugin tutorial does:

https://github.com/maidsafe/safe_examples/blob/master/comments_plugin/comments-tutorial.js#L716-L733

**Comment by theWebalyst** [comment]
Thanks Francis, that looks like it. I get something that looks like a token (but a lot longer than I'm used to!)

Bit of a clunky API don't you think? Also will need documenting. I'll close this though.

**Comment by frabrunelle** [comment]
> Bit of a clunky API don't you think?

Yes, I agree 🙂 In the [SAFE Browser – Feedback](https://forum.safedev.org/t/safe-browser-feedback/174) topic, one of the points was about improving the responses of safe-js:

> Please consider parsing and returning the responses from the APIs. At present it returns the entire response object of the fetch-isomorphic module
